name: Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  audit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24.5
      
      - name: verify dependecies
        run: go mod verify
      
      - name: build
        run: go build -v ./...
      
      - name: run go vet
        run: go vet ./...
      
      - name: install static check
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
        
      - name: run static check
        run: staticcheck ./...
      
      - name: run tests
        run: go test -race ./...
      